# Generated by Django 5.0 on 2024-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfinance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pin_hash',
            field=models.CharField(default='default_value', max_length=128),
        ),
    ]
