# Generated by Django 5.0 on 2024-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
