# Generated by Django 5.0 on 2024-03-05 03:17

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltermanagement', '0002_room_is_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('special_features', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='sheltermanagement.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
