# Generated by Django 5.0 on 2024-03-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheltermanagement', '0004_alter_bed_id_alter_room_id_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='special_features',
        ),
    ]
