# Generated by Django 5.0 on 2024-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltermanagement', '0006_guest_bed_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gender_allocation',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
