# Generated by Django 5.0 on 2024-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltermanagement', '0007_alter_room_gender_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gender_allocation',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], max_length=1),
        ),
    ]
