# Generated by Django 5.0 on 2024-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_type', models.CharField(choices=[('SHELTER', 'Shelter'), ('FOOD', 'Food'), ('HEALTH', 'Health Services'), ('HYGIENE', 'Hygiene'), ('LEGAL', 'Legal'), ('WIFI', 'Wifi'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
