# Generated by Django 5.0 on 2023-12-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('SHELTER', 'Shelter'), ('FOOD', 'Food'), ('HEALTH', 'Health Services'), ('HYGIENE', 'Hygiene'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
