# Generated by Django 5.0 on 2023-12-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistanceapp', '0002_location_address_location_description_location_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
