# Generated by Django 5.0 on 2023-12-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistanceapp', '0003_alter_location_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(default='Other', max_length=20),
        ),
    ]
